### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by ghost** [ishantchauhan710/WriterAI#1]
token expiration

**Comment by ishantchauhan710** [comment]
I have turned off the hosting server for backend of WriterAI due to monthly billings... as a result, you won't be able to use it using the link in this repository :/

If you want to use or customize WriterAI, you can follow instructions in the README file, you will need a firebase account for authentication, a cloud hosting like AWS or Linode for backend deployment, Netlify account for frontend deployment and an OpenAI account for the GPT-3 AI access!
